grid_map_filters:
  ros__parameters:
    input_topic: /grid_map
    output_topic: /filtered_map
    filters:
      filter1:
        name: buffer_normalizer
        type: gridMapFilters/BufferNormalizerFilter

      filter2:
        name: inpaint
        type: gridMapCv/InpaintFilter
        params:
          input_layer: elevation
          output_layer: elevation_inpainted
          radius: 0.1

      filter3:
        name: mean_in_radius
        type: gridMapFilters/MeanInRadiusFilter
        params:
          input_layer: elevation_inpainted
          output_layer: elevation_smooth
          radius: 0.12

      filter4:
        name: surface_normals
        type: gridMapFilters/NormalVectorsFilter
        params:
          input_layer: elevation_smooth
          output_layers_prefix: normal_vectors_
          radius: 0.15
          normal_vector_positive_axis: z

      filter5:
        name: traversability
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: traversability
          expression: (1.0 - normal_vectors_z) * 100.0
